### PR TITLE
added cost model

### PR DESCRIPTION
**Pull request by ckrk**
implementation of the Rinne et al Cost model 
Simple Python function costs contains Rinnereg
https://cris.vtt.fi/ws/files/22839641/Effects_of_turbine_technology.pdf

### CODE REVIEW

**Comment by lumbric** [comment]
Thanks for adding the costs model! We've already added the file to our [wind-repowering-usa](https://github.com/inwe-boku/wind-repowering-usa/blob/master/wind_repower_usa/costs.py) repository. There is a slightly cleaned up version. I think we can accept code duplication here. But do you want to exchange it with the cleaned up version?

**Review by lumbric — CHANGES_REQUESTED** [review]
Thanks for adding the costs model! We've already added the file to our[ wind-repowering-usa repository](https://github.com/inwe-boku/wind-repowering-usa/blob/master/wind_repower_usa/costs.py). There is a slightly cleaned up version. I think we can accept code duplication here. But do you want to exchange it with the cleaned up version?

**Comment by ckrk** [comment]
Agreed, the cleaned up version is better!

**Review by lumbric — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
